In [8]:
!pip install -U pip
!pip install torch numpy

     |████████████████████████████████| 17.0 MB 893 kB/s            


In [9]:
import numpy as np
import torch
import torch.nn as nn

from functools import partial
from dataclasses import dataclass
from collections import OrderedDict

In [18]:
class Conv2dAuto(nn.Conv2d):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.padding = (self.kernel_size[0] // 2, self.kernel_size[1] // 2) # dynamic add padding based on the kernel_size

        # Draw this out on a conv layer

In [19]:
conv3x3 = partial(Conv2dAuto, kernel_size=3, bias=False)  

In [68]:
a = conv3x3(1,64)

In [76]:
b = conv3x3(1,64)

In [74]:
torch.tensor(np.ones([1,1,24,24]))

tensor([[[[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
           1., 1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
           1., 1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
           1., 1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
           1., 1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
           1., 1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
           1., 1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
           1., 1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
           1., 1., 1., 1., 1., 1., 1.],
          [1., 1., 1., 1., 1., 1., 1., 1., 1., 1

In [73]:
a(torch.tensor(np.ones([1,1,24,24])))

tensor([[[[-0.0107,  0.2835,  0.2835,  ...,  0.2835,  0.2835,  0.0433],
          [-0.0122,  0.5976,  0.5976,  ...,  0.5976,  0.5976,  0.1302],
          [-0.0122,  0.5976,  0.5976,  ...,  0.5976,  0.5976,  0.1302],
          ...,
          [-0.0122,  0.5976,  0.5976,  ...,  0.5976,  0.5976,  0.1302],
          [-0.0122,  0.5976,  0.5976,  ...,  0.5976,  0.5976,  0.1302],
          [ 0.0730,  0.4474,  0.4474,  ...,  0.4474,  0.4474,  0.0558]],

         [[ 0.1568,  0.0384,  0.0384,  ...,  0.0384,  0.0384, -0.3537],
          [ 0.1874,  0.1528,  0.1528,  ...,  0.1528,  0.1528, -0.0078],
          [ 0.1874,  0.1528,  0.1528,  ...,  0.1528,  0.1528, -0.0078],
          ...,
          [ 0.1874,  0.1528,  0.1528,  ...,  0.1528,  0.1528, -0.0078],
          [ 0.1874,  0.1528,  0.1528,  ...,  0.1528,  0.1528, -0.0078],
          [ 0.0311,  0.2231,  0.2231,  ...,  0.2231,  0.2231,  0.1694]],

         [[-0.7014, -0.5925, -0.5925,  ..., -0.5925, -0.5925, -0.2795],
          [-0.9639, -0.7053, -

In [77]:
b(torch.tensor(np.ones([1,1,24,24])))

tensor([[[[ 0.4364,  0.5427,  0.5427,  ...,  0.5427,  0.5427,  0.2737],
          [ 0.5661,  0.8077,  0.8077,  ...,  0.8077,  0.8077,  0.5807],
          [ 0.5661,  0.8077,  0.8077,  ...,  0.8077,  0.8077,  0.5807],
          ...,
          [ 0.5661,  0.8077,  0.8077,  ...,  0.8077,  0.8077,  0.5807],
          [ 0.5661,  0.8077,  0.8077,  ...,  0.8077,  0.8077,  0.5807],
          [ 0.2787,  0.5318,  0.5318,  ...,  0.5318,  0.5318,  0.6234]],

         [[-0.0129,  0.0519,  0.0519,  ...,  0.0519,  0.0519,  0.2116],
          [-0.3122, -0.5632, -0.5632,  ..., -0.5632, -0.5632, -0.1168],
          [-0.3122, -0.5632, -0.5632,  ..., -0.5632, -0.5632, -0.1168],
          ...,
          [-0.3122, -0.5632, -0.5632,  ..., -0.5632, -0.5632, -0.1168],
          [-0.3122, -0.5632, -0.5632,  ..., -0.5632, -0.5632, -0.1168],
          [-0.0160, -0.2755, -0.2755,  ..., -0.2755, -0.2755, -0.1030]],

         [[ 0.0988, -0.0991, -0.0991,  ..., -0.0991, -0.0991,  0.1296],
          [-0.0297, -0.2281, -

In [32]:
conv = conv3x3(in_channels=32, out_channels=64)
print(conv)
del conv

Conv2dAuto(32, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)


In [31]:
conv.padding

(1, 1)

In [33]:
class ResidualBlock(nn.Module):
    def __init__(self, in_channels, out_channels):
        super().__init__()
        self.in_channels, self.out_channels =  in_channels, out_channels
        self.blocks = nn.Identity()
        self.shortcut = nn.Identity()   
    
    def forward(self, x):
        residual = x
        if self.should_apply_shortcut: residual = self.shortcut(x)
        x = self.blocks(x)
        x += residual
        return x
    
    @property
    def should_apply_shortcut(self):
        return self.in_channels != self.out_channels

In [43]:
ResidualBlock(32, 32)

11

In [50]:
dummy = torch.ones((1, 1, 1, 1))

block = ResidualBlock(1, 64)
block(dummy)

tensor([[[[2.]]]])

In [52]:
from collections import OrderedDict

class ResNetResidualBlock(ResidualBlock):
    def __init__(self, in_channels, out_channels, expansion=1, downsampling=1, conv=conv3x3, *args, **kwargs):
        super().__init__(in_channels, out_channels)
        self.expansion, self.downsampling, self.conv = expansion, downsampling, conv
        self.shortcut = nn.Sequential(OrderedDict(
        {
            'conv' : nn.Conv2d(self.in_channels, self.expanded_channels, kernel_size=1,
                      stride=self.downsampling, bias=False),
            'bn' : nn.BatchNorm2d(self.expanded_channels)
            
        })) if self.should_apply_shortcut else None
        
        
    @property
    def expanded_channels(self):
        return self.out_channels * self.expansion
    
    @property
    def should_apply_shortcut(self):
        return self.in_channels != self.expanded_channels

In [58]:
temp = ResNetResidualBlock(4, 4)

In [60]:
temp(-5)

-10

In [53]:
from collections import OrderedDict
def conv_bn(in_channels, out_channels, conv, *args, **kwargs):
    return nn.Sequential(OrderedDict({'conv': conv(in_channels, out_channels, *args, **kwargs), 
                          'bn': nn.BatchNorm2d(out_channels) }))

In [54]:
conv_bn(3, 3, nn.Conv2d, kernel_size=3)

Sequential(
  (conv): Conv2d(3, 3, kernel_size=(3, 3), stride=(1, 1))
  (bn): BatchNorm2d(3, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
)

In [55]:
class ResNetBasicBlock(ResNetResidualBlock):
    expansion = 1
    def __init__(self, in_channels, out_channels, activation=nn.ReLU, *args, **kwargs):
        super().__init__(in_channels, out_channels, *args, **kwargs)
        self.blocks = nn.Sequential(
            conv_bn(self.in_channels, self.out_channels, conv=self.conv, bias=False, stride=self.downsampling),
            activation(),
            conv_bn(self.out_channels, self.expanded_channels, conv=self.conv, bias=False),
        )

In [61]:
block(dummy).shape

torch.Size([1, 64, 224, 224])

In [62]:
block(dummy)

tensor([[[[ 3.4367e+00,  3.6397e+00,  7.8945e-01,  ...,  7.8945e-01,
           -2.1659e-01, -1.1817e+01],
          [-1.0512e+01, -8.3684e+00, -9.3123e+00,  ..., -9.3123e+00,
           -3.0347e+00, -8.5658e+00],
          [-4.7239e+00,  1.7738e-01,  9.3146e-02,  ...,  9.3146e-02,
            2.3099e+00, -5.3576e+00],
          ...,
          [-4.7239e+00,  1.7738e-01,  9.3146e-02,  ...,  9.3146e-02,
            2.3099e+00, -5.3576e+00],
          [-2.7987e-01,  4.5152e+00,  3.9055e+00,  ...,  3.9055e+00,
            1.7787e+00, -2.5194e+00],
          [-7.6404e+00, -8.8866e+00, -8.0001e+00,  ..., -8.0001e+00,
           -9.1045e+00, -4.1347e+00]],

         [[ 6.5132e+00,  9.3447e+00,  3.0498e+00,  ...,  3.0498e+00,
            3.5772e+00,  4.0905e+00],
          [ 4.7000e-01, -4.1295e-01, -4.6543e+00,  ..., -4.6543e+00,
           -1.0463e+01, -5.0076e+00],
          [ 4.7638e+00,  2.1124e+00,  2.9177e-02,  ...,  2.9177e-02,
           -3.0361e+00,  2.5984e+00],
          ...,
     

In [56]:
dummy = torch.ones((1, 32, 224, 224))

block = ResNetBasicBlock(32, 64)
block(dummy).shape
print(block)

ResNetBasicBlock(
  (blocks): Sequential(
    (0): Sequential(
      (conv): Conv2dAuto(32, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    )
    (1): ReLU()
    (2): Sequential(
      (conv): Conv2dAuto(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    )
  )
  (shortcut): Sequential(
    (conv): Conv2d(32, 64, kernel_size=(1, 1), stride=(1, 1), bias=False)
    (bn): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  )
)
